version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: x_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - x

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
    
networks:
  x:
    driver: bridge